// filepath: c:\Users\LENOVO\Documents\PT\New folder\socialog\src\app\metadata.ts
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Socialog",
  description: "Generated by create next app",
};
